server:
  port: 9090
spring:
  application:
    name: demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root123



logging:
  config: classpath:log4j2.xml
#logging:
#  level:
#    org.springfromework: debug

app:
  key-file-location: classpath:keys.txt;

